version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:80

  nginx:
    image: nginx:latest
    container_name: vue-nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app

